version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django_project
      POSTGRES_USER: django_project
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  
  redis:
    image: redis:latest
    restart: always

  # Celery worker service
  worker:
    build: .
    command: celery -A new_filer worker --loglevel=info
    depends_on:
      - web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_database
      - DJANGO_SETTINGS_MODULE=new_filer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Celery beat service
  beat:
    build: .
    command: celery -A new_filer beat --loglevel=info
    depends_on:
      - web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_database
      - DJANGO_SETTINGS_MODULE=new_filer.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data: